#ifndef SDKCONFIG_H
#define SDKCONFIG_H

// ESP32 SDK Configuration for C.A.R.E. High-Performance Radar
// This file provides missing SDK configuration for PlatformIO compilation

// FreeRTOS Configuration
#define CONFIG_FREERTOS_HZ 1000
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_USE_STATS_FORMATTING_FUNCTIONS 1
#define CONFIG_FREERTOS_USE_TRACE_FACILITY 1
#define CONFIG_FREERTOS_VTASKLIST_INCLUDE_COREID 1

// ESP32 CPU Configuration
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_240 1
#define CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ 240

// SPIRAM Configuration
#define CONFIG_SPIRAM_SUPPORT 1
#define CONFIG_SPIRAM_USE_MALLOC 1
#define CONFIG_SPIRAM_USE_CAPS_ALLOC 1
#define CONFIG_SPIRAM_USE_MEMMAP 1
#define CONFIG_SPIRAM_MEMTEST 1
#define CONFIG_SPIRAM_BANKSWITCH_ENABLE 1
#define CONFIG_SPIRAM_2T_MODE 1
#define CONFIG_SPIRAM_SPEED_80M 1
#define CONFIG_SPIRAM_IGNORE_NOTFOUND 1
#define CONFIG_SPIRAM_WORKING_AREA_DRAM_OVERLAP 1
#define CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP 1
#define CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL 0
#define CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL 0
#define CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY 1
#define CONFIG_SPIRAM_ALLOW_NOINIT_SEG_EXTERNAL_MEMORY 1
#define CONFIG_SPIRAM_CACHE_WORKAROUND 1

// WiFi Configuration
#define CONFIG_ESP32_WIFI_ENABLED 1
#define CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM 10
#define CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM 32
#define CONFIG_ESP32_WIFI_DYNAMIC_TX_BUFFER_NUM 32

// UART Configuration
#define CONFIG_UART_ISR_IN_IRAM 1

// Flash Configuration
#define CONFIG_SPI_FLASH_USE_LEGACY_IMPL 1
#define CONFIG_SPI_FLASH_ENABLE_COUNTERS 1

// Memory Configuration
#define CONFIG_ESP32_SPIRAM_SUPPORT 1
#define CONFIG_SPIRAM_BOOT_INIT 1
#define CONFIG_SPIRAM_USE_MALLOC 1
#define CONFIG_SPIRAM_USE_CAPS_ALLOC 1
#define CONFIG_SPIRAM_USE_MEMMAP 1
#define CONFIG_SPIRAM_MEMTEST 1
#define CONFIG_SPIRAM_BANKSWITCH_ENABLE 1
#define CONFIG_SPIRAM_2T_MODE 1
#define CONFIG_SPIRAM_SPEED_80M 1
#define CONFIG_SPIRAM_IGNORE_NOTFOUND 1
#define CONFIG_SPIRAM_WORKING_AREA_DRAM_OVERLAP 1
#define CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP 1
#define CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL 0
#define CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL 0
#define CONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY 1
#define CONFIG_SPIRAM_ALLOW_NOINIT_SEG_EXTERNAL_MEMORY 1
#define CONFIG_SPIRAM_CACHE_WORKAROUND 1

// Task Watchdog Configuration
#define CONFIG_ESP_TASK_WDT 1
#define CONFIG_ESP_TASK_WDT_TIMEOUT_S 5
#define CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0 1
#define CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1 1

// Log Configuration
#define CONFIG_LOG_DEFAULT_LEVEL_INFO 1
#define CONFIG_LOG_DEFAULT_LEVEL 3

// Assert Configuration
#define CONFIG_ASSERT_LEVEL 2

#endif // SDKCONFIG_H
